### ISSUE TITLE
Graphene Server - exited with code 137 when called from multiple processes

### ISSUE THREAD

**Issue by jbecke** [Lambda-3/Graphene#24]
I'm trying to generate OpenIE tuples for a large corpus of text. To parallelize this I am using Python's multiprocessing library. However, as soon as the process pool has more than one process (i.e. more than one process making POST requests concurrently) the server exists with exit code 137. A few questions...

Does the Graphene server use a thread pool or is it single-threaded?
What does exit code 137 mean?

And most importantly, if not by using the server, what's the fastest way to annotate a 500 MB text file? Thanks!

**Comment by jbecke** [comment]
Still not sure what the issue is. Problem still occurs when coreference is turned off. I made a simple REST API using Spark Java here: https://github.com/NPCai/REST-graphene, which doesn't have the same issue.

**Comment by bermeitinger-b** [comment]
Error code 137 (128 + 9) means that the process was killed (SIGKILL) by another process; it can't kill itself. We do not use any exit signals.
It might have been a OOM Killer that experiences a high memory usage by the Graphene process and kills it.
I did small tests and couldn't reproduce this issue.

Supporting parallel requests was not something Graphene was designed for or initially planned to include, so we might have to change something specific to improve this. The reasoning for this is, that CoreNLP and the previously used OpenIE-framework was so heavyweight on memory and CPU that it didn't make sense to use parallel requests because it wouldn't speed up the process.

You can use the commandline interface without the service to run it on your file, although, I think that running it on 500MB of text might be too much. But I'll be happy to be proven otherwise.
