### ISSUE TITLE
using custom NER

### ISSUE THREAD

**Issue by vlordier** [Lambda-3/Graphene#25]
Could you point out how you would go about using a custom trained NER, with domain-specific entities ?

**Comment by Mischn** [comment]
Hello Vincent,

please correct me if this does not answer your question, but I assume you want to know how one can extract **named entities** as relational arguments.

In a nutshell, the approach of Graphene is based on a prior **sentence-simplification process**, where really complex sentences are recursively transformed into simpler ones. After that, **subject-predicate-object relationships** are extracted from these **simpler sentences** (for more details [see the Graphene publication](https://github.com/Lambda-3/Graphene/blob/master/paper/COLING2018_Graphene.pdf)).

In this way, our product acts as preprocessing framework for any system that is capable of extracting subject-predicate-object relationships from texts.
So, in order to extract (domain-specific) NEs as arguments, you can simply implement your **own RelationExtractor** and use it as the RelationExtraction component inside of Graphene.

Here is what you will have to do:

- You need an RelationExtractor that will identify named entities (using NER) and their relationships in a sentence. You can implement your own Extractor or modify one of the already available implementations in the package `org.lambda3.graphene.core.relation_extraction.impl`
- Ensure that your Implementation inherits from the class `org.lambda3.graphene.core.relation_extraction.RelationExtractor`
- To use your implementation in the framework, you need to specify your new implementation in the configuration file (`reference.conf`). Simply change the attribute:

`relation-extractor = org.lambda3.graphene.core.relation_extraction.impl.HeadRelationExtractor`
to point to your new RelationExtractor-class:
`relation-extractor = org.lambda3.graphene.core.relation_extraction.impl.MyNERRelationExtractor`

**Comment by vlordier** [comment]
All clear Matthias ! Thank you :)
