### ISSUE TITLE
Usage for different language

### ISSUE THREAD

**Issue by MichalGabonay** [Lambda-3/Graphene#33]
It is a possibility to somehow use this project for different languages from English? I need OpenIE for Czech and Slovak language. Can be just used another language model? If yes, are there some special requirements for this language model? How big dependency is on WordNet? 

Thank you.

**Comment by Mischn** [comment]
Hello Michal,

At this moment, we do not support other languages than English.
We are working on transporting our approach to German language, but we do not consider other languages for now.

Best
Matthias

**Comment by MichalGabonay** [comment]
Thank you for replay. I meant it, if there is possible to transform it by myself, I would do it. And I want to ask if it can be done without recreating the whole project. If there is some not so hard (of course not so easy) way, how to add a support for other languages. 

Thank you,
Michal

**Comment by Mischn** [comment]
Hello Michal,

If you want to modify `Graphene` in order to process other languages, I suggest to modify the `DiscourseSimplification` project and implement your own rule patterns that are specific for your language.

Each rule needs to extend the `ExtractionRule` class. You can use the implemented rules in the package `org.lambda3.text.simplification.discourse.runner.discourse_tree.extraction.rules` as templates.
For each rule, you have to implement the `public Optional<Extraction> extract(Leaf leaf)` function which will split up a leaf node in the current DiscourseTree into smaller (simplified) sentences. The text of the leaf node is provided by `leaf.getText()` or the corresponding parse tree `leaf.getParseTree()`.
Note that this is currently bound to the Stanford's parse tree which is generated by the Stanford Lexical Parser (see `org.lambda3.text.simplification.discourse.utils.parseTree.ParseTreeParser`). You may want to use another parser instead.

The implemented rules are processed in a hierarchical fashion. You can specify their execution order in the configuration file:
`DiscourseSimplification/src/main/resources/reference.conf`. The first (topmost) rule pattern that will match (returns a non-empty `Optional<Extraction>` object) will split up the leaf nodes into smaller sentences (the `constituents` of the `Extraction` class). Then, the algorithm will continue by processing these new generated sentences.

Best
Matthias
